---
title: "HW#2"
author: "Daniil Deych"
date: "`r Sys.Date()`"
output: html_document
---
### HW#2

## Problem #1

```{r}
library(tidyverse)
library(ggplot2)
library(modelr)
library(rsample)
library(mosaic)
library(caret)
library(purrr)
data(SaratogaHouses)

saratoga_split = initial_split(SaratogaHouses, prop = 0.8)
saratoga_train = training(saratoga_split)
saratoga_test = testing(saratoga_split)
```

# "Medium" model

```{r}
lm_medium = lm(price ~ . - pctCollege - sewer - waterfront - landValue - newConstruction, data=saratoga_train)

rmse(lm_medium, saratoga_test)
```
# "Improved" linear model

```{r}
lm_improved = lm(price ~ . - bathrooms - pctCollege - fireplaces + newConstruction*age + rooms*bedrooms + fireplaces*bedrooms + lotSize*landValue, data = saratoga_test)

rmse(lm_improved, saratoga_test)
```

# KNN Model

```{r}
xtrain = model.matrix(~ . - 1, data=saratoga_train) %>%
  data.frame(xtrain)
xtest = model.matrix(~ . - 1, data=saratoga_test) %>%
  data.frame(xtest)

ytrain = saratoga_train$price
ytest = saratoga_test$price

scale_train = apply(xtrain, 2, sd)
xtilde_train = scale(xtrain, scale = scale_train) %>%
  data.frame(xtilde_train)
xtilde_test = scale(xtest, scale = scale_train) %>%
  data.frame(xtilde_test)

knn_saratoga = knnreg(price ~ lotSize, data=xtilde_train_df, k=200)
modelr::rmse(knn_saratoga, xtilde_test_df)

head(xtrain, 2)
head(xtilde_train_df, 2)
```

