---
title: "HW#2"
author: "Daniil Deych, Reilly Blakeslee, Alex Mykietyn"
date: "`r Sys.Date()`"
output: html_document
---
#### HW#2

### Problem #1

```{r}
library(tidyverse)
library(ggplot2)
library(modelr)
library(rsample)
library(mosaic)
library(caret)
library(purrr)
data(SaratogaHouses)

saratoga_split = initial_split(SaratogaHouses, prop = 0.8)
saratoga_train = training(saratoga_split)
saratoga_test = testing(saratoga_split)
```

# "Medium" model

```{r}
lm_medium = lm(price ~ . - pctCollege - sewer - waterfront - landValue - newConstruction, data=saratoga_train)

rmse(lm_medium, saratoga_test)
```
# "Improved" linear model

```{r}
lm_improved = lm(price ~ . - bathrooms - pctCollege - fireplaces + newConstruction*age + rooms*bedrooms + fireplaces*bedrooms + lotSize*landValue, data = saratoga_test)

rmse(lm_improved, saratoga_test)
```

# KNN Model

```{r}
saratoga_train_matrix = model.matrix(~ . - 1, data=saratoga_train)
saratoga_train_matrix = data.frame(saratoga_train_matrix)
saratoga_test_matrix = model.matrix(~ . - 1, data=saratoga_test)
saratoga_test_matrix = data.frame(saratoga_test_matrix)

ytrain = saratoga_train$price
ytest = saratoga_test$price

scale_train = apply(saratoga_train_matrix, 2, sd)

saratoga_tilde_train_matrix = scale(saratoga_train_matrix, scale = scale_train)
saratoga_tilde_train_matrix = data.frame(saratoga_tilde_train_matrix)
  
saratoga_tilde_test_matrix = scale(saratoga_test_matrix, scale = scale_train)
saratoga_tilde_test_matrix = data.frame(saratoga_tilde_test_matrix)
  
knn_saratoga_15 = knnreg(price ~ . - pctCollege - bathrooms, data=saratoga_tilde_train_matrix, k=15)
modelr::rmse(knn_saratoga_15, saratoga_tilde_test_matrix)

set.seed(30)
knn_vector = c(2:346)
knn_saratoga_train = list()
knn_saratoga_test = list()
knn_rmse_vector = c()

for (i in 2:length(knn_vector)){
  knn_saratoga_train[[i]] = knnreg(price ~ . - pctCollege - bathrooms, data=saratoga_tilde_train_matrix, k = knn_vector[i])
  knn_saratoga_test = saratoga_tilde_test_matrix %>%
    mutate(PricePredict = predict(knn_saratoga_train[[i]], saratoga_tilde_test_matrix))
  knn_rmse_vector[i] = modelr::rmse(knn_saratoga_train[[i]], saratoga_tilde_test_matrix)
}

plot(knn_vector, knn_rmse_vector)

knn_rmse_vector_df = data_frame(knn_vector, knn_rmse_vector)
```

# Optimal K = 7

```{r}
knn_saratoga_7 = knnreg(price ~ . - pctCollege - bathrooms, data=saratoga_tilde_train_matrix, k=7)
modelr::rmse(knn_saratoga_7, saratoga_tilde_test_matrix)
```


### Problem #2

### Problem #3

```{r}
library(readr)
library(dplyr)
library(MASS)
library(ISLR)
hotels_dev = read_csv("Data/hotels_dev.csv")
hotels_val = read.csv("Data/hotels_val.csv")

hotels_dev$id <- 1:nrow(hotels_dev)

hotels_dev_split = initial_split(hotels_dev, prop = 0.8)
hotels_dev_train = training(hotels_dev_split)
hotels_dev_test = testing(hotels_dev_split)

m1_hotels_dev = glm(children ~ market_segment + adults + customer_type + is_repeated_guest, data = hotels_dev_train, family = 'binomial')
m2_hotels_dev = glm(children ~ . - arrival_date, data = hotels_dev_train, family = 'binomial')
m3_hotels_dev = glm(children ~ . - arrival_date + adults*stays_in_weekend_nights + adults*meal + adults*assigned_room_type, data = hotels_dev_train, family = 'binomial')
```
##RMSE Test
```{r}
rmse(m1_hotels_dev, data = hotels_dev_test)
rmse(m2_hotels_dev, data = hotels_dev_test)
rmse(m3_hotels_dev, data = hotels_dev_test)
```
##Out-of-Sample Predict test
```{r}
phat_test_children1 = predict(m1_hotels_dev, hotels_dev_test, type = 'response')
yhat_test_children1 = ifelse(phat_test_children1 > 0.5, 1, 0)
confusion_m1 = table(y = hotels_dev_test$children, yhat = yhat_test_children1)
confusion_m1

phat_test_children2 = predict(m2_hotels_dev, hotels_dev_test, type = 'response')
yhat_test_children2 = ifelse(phat_test_children2 > 0.5, 1, 0)
confusion_m2 = table(y = hotels_dev_test$children, yhat = yhat_test_children2)
confusion_m2

phat_test_children3 = predict(m3_hotels_dev, hotels_dev_test)
yhat_test_children3 = ifelse(phat_test_children3 > 0.5, 1, 0)
confusion_m3 = table(y = hotels_dev_test$children, yhat = yhat_test_children3)
confusion_m3

table(hotels_dev_test$children)
```

```{r}
# Accuracy Calculations
m1_accuracy = sum(diag(confusion_m1))/sum(confusion_m1)
m2_accuracy = sum(diag(confusion_m2))/sum(confusion_m2)
m3_accuracy = sum(diag(confusion_m3))/sum(confusion_m3)
null_accuracy = 8276/(8276+724)

m1_accuracy
m2_accuracy
m3_accuracy
null_accuracy

# Absolute Improvement 

m1_absimpr = m1_accuracy - null_accuracy
m2_absimpr = m2_accuracy - null_accuracy
m3_absimpr = m3_accuracy - null_accuracy

# Lift

m1_lift = m1_accuracy/null_accuracy
m2_lift = m2_accuracy/null_accuracy
m3_lift = m3_accuracy/null_accuracy
```

